# Generated by Django 5.2 on 2026-02-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisreport",
            name="ai_analysis",
        ),
    ]
