# Generated by Django 5.2 on 2026-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_remove_analysisreport_ai_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="ai_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
