# Generated by Django 5.2 on 2026-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0003_analysisreport_ai_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="steps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
