# Generated by Django 5.2 on 2026-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0004_analysisreport_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="business_plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
