# Generated by Django 5.2 on 2026-02-23 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0005_analysisreport_business_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisreport",
            name="business_plan",
        ),
        migrations.CreateModel(
            name="BusinessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executive_summary", models.TextField(blank=True, null=True)),
                ("market_analysis", models.TextField(blank=True, null=True)),
                ("competitor_positioning", models.TextField(blank=True, null=True)),
                ("target_audience", models.TextField(blank=True, null=True)),
                ("revenue_model", models.TextField(blank=True, null=True)),
                ("marketing_strategy", models.TextField(blank=True, null=True)),
                ("tech_architecture", models.TextField(blank=True, null=True)),
                ("roadmap", models.JSONField(blank=True, default=list)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_plan_document",
                        to="ideas.analysisreport",
                    ),
                ),
            ],
        ),
    ]
