# Generated by Django 5.2 on 2026-02-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0006_remove_analysisreport_business_plan_businessplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessplan",
            name="report",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_plan_document",
                to="ideas.analysisreport",
            ),
        ),
    ]
